import { InjectQueue } from "@nestjs/bullmq";
import { Injectable, NotFoundException } from "@nestjs/common";
import { type Job, type JobState, type Queue } from "bullmq";

import { Message } from "@/common/constants/message";
import {
  BullMQJobState,
  type JobResult,
  JobStatus,
  type JobStatusResponse,
  JobType,
} from "@/jobs/jobs.types";
import { QueueName } from "@/queue/queue.constants";

/**
 * Service for querying the status of enqueued jobs.
 *
 * Searches both the `key-generation` and `signing` queues for a given job
 * identifier. Job identifiers are UUIDs generated by the respective enqueue
 * services; they are globally unique across both queues.
 */
@Injectable()
class JobsService {
  constructor(
    @InjectQueue(QueueName.KEY_GENERATION)
    private readonly keyGenerationQueue: Queue,
    @InjectQueue(QueueName.SIGNING)
    private readonly signingQueue: Queue,
  ) {}

  /**
   * Retrieves the current status of a job by its identifier.
   *
   * Searches the `key-generation` queue first, then the `signing` queue.
   * Throws `NotFoundException` if the job is not found in either queue.
   *
   * @param {string} jobId - The UUID returned when the job was enqueued.
   * @returns {Promise<JobStatusResponse>} A snapshot of the job's current
   *   state and result (if available).
   * @throws {NotFoundException} When no job with the given identifier exists.
   */
  async getJobStatus(jobId: string): Promise<JobStatusResponse> {
    const keyGenerationJob: Job | undefined =
      await this.keyGenerationQueue.getJob(jobId);

    if (keyGenerationJob) {
      return this.mapJobToResponse(keyGenerationJob, JobType.KEY_GENERATION);
    }

    const signingJob: Job | undefined = await this.signingQueue.getJob(jobId);

    if (signingJob) {
      return this.mapJobToResponse(signingJob, JobType.SIGNING);
    }

    throw new NotFoundException(Message.JOB_NOT_FOUND(jobId));
  }

  /**
   * Maps a BullMQ `Job` instance to the public `JobStatusResponse` shape.
   *
   * @param {Job} job - The BullMQ job retrieved from the queue.
   * @param {JobType} type - Whether this is a key-generation or signing job.
   * @returns {Promise<JobStatusResponse>} The formatted response DTO.
   */
  private async mapJobToResponse(
    job: Job,
    type: JobType,
  ): Promise<JobStatusResponse> {
    const bullmqState: JobState | "unknown" = await job.getState();
    const status: JobStatus = this.mapBullMQState(bullmqState);

    const createdAt: string = new Date(job.timestamp).toISOString();
    const updatedAt: string = new Date(
      job.finishedOn ?? job.processedOn ?? job.timestamp,
    ).toISOString();

    if (!job.id) throw new Error("Job is missing its identifier.");

    return {
      jobId: job.id,
      type,
      status,
      result:
        status === JobStatus.COMPLETED
          ? this.validateJobResult(job.returnvalue)
          : null,
      error: status === JobStatus.FAILED ? (job.failedReason ?? null) : null,
      createdAt,
      updatedAt,
    };
  }

  /**
   * Validates that a job's return value is a plausible `JobResult` before
   * exposing it through the API.
   *
   * @param {unknown} value - The raw `job.returnvalue` from BullMQ.
   * @returns {JobResult} The validated result.
   * @throws {Error} When the return value is not a valid object.
   */
  private validateJobResult(value: unknown): JobResult {
    if (typeof value !== "object" || value === null) {
      throw new Error("Job completed with an invalid result.");
    }
    return value as JobResult;
  }

  /**
   * Translates a BullMQ internal state string into the public `JobStatus`
   * enum.
   *
   * BullMQ states beyond `active`, `completed`, and `failed` (e.g. `waiting`,
   * `delayed`, `prioritized`, `waiting-children`) are all mapped to `pending`
   * since they represent pre-processing states from the client's perspective.
   *
   * @param {JobState | "unknown"} bullmqState - The state string returned by
   *   `Job.getState()`.
   * @returns {JobStatus} The corresponding `JobStatus` value.
   */
  private mapBullMQState(bullmqState: JobState | "unknown"): JobStatus {
    switch (bullmqState) {
      case BullMQJobState.ACTIVE:
        return JobStatus.PROCESSING;
      case BullMQJobState.COMPLETED:
        return JobStatus.COMPLETED;
      case BullMQJobState.FAILED:
        return JobStatus.FAILED;
      default:
        return JobStatus.PENDING;
    }
  }
}

export { JobsService };
